# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

os:
  - linux
  - osx

go:
  - master
  - 1.9.x

install:
  - make deps

script:
  #  - go test
  - make build
  # - make publish

cache:
  directories:
    - $GOPATH/src/gx

notifications:
  email: false
 
  