# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

os:
  - linux
  - osx

go:
  - master
  - 1.9.x

git:
  depth: 1

notifications:
  email: false

before_script:
  - make deps

script:
  - go build main.go
 
  